// <auto-generated />
namespace OlympusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class eliminarestados2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eliminarestados2));
        
        string IMigrationMetadata.Id
        {
            get { return "201501260016035_eliminarestados2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
